je-me-presente/config/routes.rb
Rails.application.routes.draw do


  root to: 'static_pages#home'
  get '/contact', to: 'static_pages#contact'
  # get '/description(/:name)', to: 'static_pages#about', as: 'about'

  get '/about', to: 'static_pages#about', as: 'about'

  get '/about/max', to: 'static_pages#max', as: 'max'

  get '/about/bab', to: 'static_pages#bab', as: 'bab'

  get '/about/team_bdx', to: 'static_pages#team_bdx', as: 'team_bdx'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

je-me-presente/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def redirect

    puts "kiki"

  end

end

je-me-presente/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about

    # @name = params[:name]

  end

  def bab

  end

  def team_bdx

  end

  def max

  end

end

je-me-presente/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App de la team BDX</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>

  </head>

  <body>


      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="http://www.bordeaux.fr/" target="blank">Team BDX</a>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="<%= root_path%>">Home<span class="sr-only"></span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= contact_path%>">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= about_path%>">About</a>
            </li>
          </ul>
        </div>
      </nav>

    <p style="margin-top: 50px"> </p>

    <%= yield %>

  </body>
</html>

je-me-presente/app/views/static_pages/about.html.erb
    <div class="content">
      <h1 class="title">About ...</h1>

      <p>
        Voici les liens des descriptions de chacun de nous !
      </p>


      <p>
        Liens :<br>
        <a href="<%= bab_path %>">Vers chez Bab</a>
        <br>
        <a href="<%= max_path %>">Vers chez Max</a>
        <br>
        <a href="<%= team_bdx_path %>">Vers la team</a>
      </p>
      <br>
      <p>Made with 🧡.</p>
    </div>

je-me-presente/app/views/static_pages/bab.html.erb
    <div class="content">
      <h1 class="title">About ... Bab</h1>

      <p>
        🙃
      </p>


      <p>
        Liens :<br>
        <a href="<%= max_path %>">Vers chez Max</a>
        <br>
        <a href="<%= team_bdx_path %>">Vers la team</a>
      </p>
      <br>
      <p>Made with 🧡.</p>
    </div>

je-me-presente/app/views/static_pages/contact.html.erb
    <div class="content">
      <h1 class="title">Contact ...</h1>

      <p>
        Nos comptes Github :
      </p>


      <p>
        <h3><a href="https://github.com/DaTikh" target="blank">@bab</a></h3>
        <h3><a href="https://github.com/iMassim0" target="blank">@massimo</a></h3>

      </p>
      <br>
      <p>Made with 🧡.</p>
    </div>

je-me-presente/app/views/static_pages/home.html.erb
    <div class="content">
      <h1 class="title">Welcome Home</h1>

      <p>
        Not a very beautful website, but functional ...
      </p>



      <br>
      <p>Made with 🧡.</p>
    </div>

je-me-presente/app/views/static_pages/max.html.erb
    <div class="content">
      <h1 class="title">About ... Max </h1>

      <p>
        🙈
      </p>


      <p>
        Liens :<br>
        <a href="<%= bab_path %>">Vers chez Bab</a>
        <br>
        <a href="<%= team_bdx_path %>">Vers la team</a>
      </p>
      <br>
      <p>Made with 🧡.</p>
    </div>

je-me-presente/app/views/static_pages/team_bdx.html.erb
    <div class="content">
      <h1 class="title">About ... Team BDX</h1>

      <p>
        💻
      </p>


      <p>
        Liens :<br>
        <a href="<%= max_path %>">Vers chez Max</a>
        <br>
        <a href="<%= bab_path %>">Vers chez Bab</a>

      </p>
      <br>
      <p>Made with 🧡.</p>
    </div>