site-backend/config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#index'  # Définition de la page d'accueil
  get 'create_user', to: 'users#new', as: 'creation'  # Routing de la page création de profil sur le controller Users
  post 'create_user', to: 'users#new_post', as: 'creation_post'  # Lors de l'envoi du formulaire
  get 'users/error', to: "users#error", as: 'error'  # Routing du message d'erreur
  get 'users(/:username)', to: "users#show", as: 'user'  # Routing du profil utilisateur

end

site-backend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

site-backend/app/models/user.rb
class User < ApplicationRecord

  validates :username,                            # Condition de validation d'un enregistrement pour le username
            presence: true,                       # Le champ ne doit pas être vide
            uniqueness: true,                     # Il ne doit pas déjà exister dans la database
            format: { with: /\A[-a-zA-Z]+\z/ };   # Il est composé de lettres et peut contenir un tiret

end

site-backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

site-backend/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index  # Render la page d'accueil
  end

end

site-backend/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new  # Render la view "Create_user"
  end

  def new_post  # Se déclenche à l'envoi du FORM
    @user = User.new  # On lance la création d'un nouvel User
    @user.username = params[:username]  # On sélectionne la value associée au pseudo
    @user.bio = params[:bio]  # On sélectionne ensuite la bio
    @user.save  # On enregistre le nouvel User
      if @user == User.last  # On teste si l'enregistrement est réussi
        redirect_to user_path"#{@user.username}"  # Si OK on redirige sur la page du nouveal User
      else
        redirect_to error_path  # Sinon on envoie sur le message d'erreur
      end
  end

  def error  # Render le message d'erreur
  end

  def show  # Render la view du profil utilisateur
    @user = User.find_by(username: params[:username])  # On trouve l'utilisateur par son pseudo
  end


end

site-backend/app/helpers/application_helper.rb
module ApplicationHelper
end

site-backend/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

site-backend/app/helpers/users_helper.rb
module UsersHelper
end

site-backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Site Backend - THP BDX</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

site-backend/app/views/static_pages/index.html.erb
<h1>ACCUEIL DU SITE</h1>
<a href="<%= creation_path %>"><img src="/THP_BDX.png" alt="Logo Team BORDEAUX" /></a>
<h3>Pour créer un nouvel utilisateur, clique sur l'image !! :)</h3>

site-backend/app/views/users/error.html.erb
<h2>ERREUR DE SAISIE !</h2>
<p>Votre nom d'utilisateur ne peut contenir que des lettres, sans espace.</p>
<p>Pour retourner sur la page de création d'utilisateur, <a href="<%= creation_path %>">cliquez ici</a> !</p>

site-backend/app/views/users/new.html.erb
<h1>Création d'utilisateur</h1>

<h2>Bienvenue sur la page de création d'un nouvel utilisateur !</h2>

<form action="/create_user" method="post" style="padding: 10px">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <strong>Ton prénom :</strong><br>
  <input type="text" name="username"><br><br>
  <strong>Ta bio :</strong><br>
  <textarea type="text" name="bio" rows="3" cols="40">Ecris un petit mot à propos de toi ici...</textarea><br><br>
  <input type="submit" value="Envoyer">
</form>

site-backend/app/views/users/show.html.erb
<h1>Profil Utilisateur</h1>

<h2>Bienvenue <%= @user.username %> !!</h2>

<p>Voici quelques mots pour te décrire :<br>
<%= @user.bio %></p>